// Generated by v0 AI: https://v0.dev/
"use client"

import React, { useState } from "react"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Home, Menu, Settings, User } from "lucide-react"
import {logout} from "@/lib/actions/auth";
import logo from "@/public/vercel.svg";
import Image from "next/image";


const navItems = [
  { name: "Items", icon: Home, href: "/items" },
  { name: "Settings", icon: Settings, href: "/settings" },
]

export default function CombinedNavbar({ children }: Readonly<{ children: React.ReactNode; }>) {
  const pathname = usePathname()
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)

  const NavContent = () => (
    <ScrollArea className="h-[calc(100vh-4rem)] py-6 pl-6 pr-6">
      <div className="space-y-4">
        <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
          Menu
        </h2>
        <div className="space-y-1">
          {navItems.map((item) => (
            <Button
              key={item.name}
              variant={pathname === item.href ? "secondary" : "ghost"}
              className={"w-full justify-start " + (pathname === item.href ? "bg-slate-300" : "")}
              asChild
            >
              <Link href={item.href} onClick={() => setIsMobileMenuOpen(false)}>
                <item.icon className="mr-2 h-4 w-4" />
                {item.name}
              </Link>
            </Button>
          ))}
        </div>
      </div>
    </ScrollArea>
  )

  return (
    <div className="flex h-screen flex-col">
      {/* Top Bar */}
      <header className="sticky top-0 z-40 w-full border-b bg-background">
        <div className="flex h-16 items-center justify-between px-4">
          <div className="flex items-center">
            {/* Mobile menu button */}
            <Sheet open={isMobileMenuOpen} onOpenChange={setIsMobileMenuOpen}>
              <SheetTrigger asChild>
                <Button
                  variant="outline"
                  size="icon"
                  className="mr-2 md:hidden"
                >
                  <Menu className="h-6 w-6" />
                </Button>
              </SheetTrigger>
              <SheetContent side="left" className="w-56 p-0">
                <div className="flex h-full flex-col">
                  <div className="px-4 py-2">
                    <Image
                      src={logo}
                      alt="Vercel Logo"
                      className="py-2 px-2"
                      width={100}
                      height={24}
                      priority
                    />
                  </div>
                  <NavContent />
                </div>
              </SheetContent>
            </Sheet>
            <h1 className="text-lg font-semibold">Next Game Library</h1>
          </div>
          <div className="flex items-center space-x-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="relative h-8 w-8 rounded-full">
                  <Avatar className="h-8 w-8">
                    <AvatarImage src="/placeholder-avatar.jpg" alt="@johndoe" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56" align="end" forceMount>
                <DropdownMenuLabel className="font-normal">
                  <div className="flex flex-col space-y-1">
                    <p className="text-sm font-medium leading-none">John Doe</p>
                    <p className="text-xs leading-none text-muted-foreground">
                      john.doe@example.com
                    </p>
                  </div>
                </DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <User className="mr-2 h-4 w-4" />
                  <span>Profile</span>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Settings className="mr-2 h-4 w-4" />
                  <span>Settings</span>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <form className="w-full" action={logout}>
                    <Button className="w-full">Log out</Button>
                  </form>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>

      {/* Main content area with sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Desktop Sidebar */}
        <aside className="hidden w-64 border-r bg-gray-100/40 md:block">
          <div className="flex h-full flex-col">
            <div className="px-4 py-2">
              <Image
                src={logo}
                alt="Vercel Logo"
                className="p-2"
                height={26}
                priority
              />
            </div>
            <NavContent />
          </div>
        </aside>

        {/* Main content */}
        <main className="flex-1 overflow-y-auto p-4">
          {children}
        </main>
      </div>
    </div>
  )
}